name: Build

on:
  push:
    branches:
      - main

# the follow line allow this script to be started manually.
  workflow_dispatch:

jobs:
  build:
    # This job will run on ubuntu virtual machine
    runs-on: ubuntu-latest
    steps:
      # Setup Java environment in order to build the Android app.
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"

      # Setup the flutter environment.
      - uses: subosito/flutter-action@v1
        with:
          # channel: 'beta' # 'dev', 'alpha', default to: 'stable'
          flutter-version: "2.5" # you can also specify exact version of flutter

      # Flutter update
      - run: flutter update

      
      # Get flutter dependencies.
      - run: flutter pub get

      # Build appbundle.
      - run: flutter build appbundle --target-platform android-arm,android-arm64,android-x64 --no-sound-null-safety

      - run: zip -d build/app/outputs/bundle/release/app-release.aab META-INF/\*

      - uses: r0adkll/sign-android-release@v1
        name: Sign app APK

        id: sign_app # ID used to access action output
        with:
          releaseDirectory: build/app/outputs/bundle/release
          signingKeyBase64: ${{ secrets.KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      # Upload generated apk to the artifacts.
      - uses: actions/upload-artifact@v1
        name: Upload Artifact
        with:
          name: release-aab
          path: build/app/outputs/bundle/release/app-release.aab
